# Generated by Django 6.0.5 on 2026-06-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebooking',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
