# Generated by Django 6.0.5 on 2026-06-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'user__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='demoslot',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherprofile'),
        ),
    ]
